### ISSUE TITLE
setState() not changing the "value" props in Editor.render()? 

### ISSUE THREAD

**Issue by tomkcey** [vankop/jsoneditor-react#13]
Greetings,

In this code, when I change the state of the component with setState(), it does go into the render() method, but does not actually change the display to reflect the new state.

I placed the this.state in the "value" props of the Editor component.

Here's a link to the code: [demo-jsoneditor-react](https://github.com/tomkcey/demo-jsoneditor-react)

**Comment by Victordmdb** [comment]
Did you manage to figure this out? I'm stuck at this too. It currently has a shouldComponentUpdate which only updates with changes to htmlElementProps.

To make it worked I added a key prop which changes if the value changes since this forces a new component to be generated. Not a great solution but nothing else seemed to work.

**Comment by tomkcey** [comment]
Nah, still waiting to see how he managed that. I'll return to it this afternoon.

**Comment by vankop** [comment]
https://github.com/vankop/jsoneditor-react/issues/3

**Comment by vankop** [comment]
As discussed there you can get reference of JSONEditor and change state manually, because of breaking functionality. For changing state use https://github.com/vankop/jsoneditor-react/issues/4#issuecomment-419638767
