### ISSUE TITLE
How to set height of the Json Editor Code area from the code?

### ISSUE THREAD

**Issue by himanshupareek** [vankop/jsoneditor-react#7]

**Comment by himanshupareek** [comment]
I could solve it by overriding the style in my css class:

div.jsoneditor{
    height: 800px !important;
}

**Comment by vankop** [comment]
@himanshupareek actually you can pass any prop  supported by [jsoneditor API](https://github.com/josdejong/jsoneditor/blob/master/docs/api.md), due to: https://github.com/vankop/jsoneditor-react/blob/master/src/Editor.jsx#L137

As I see there is no height property for editor, so my suggestion is to use your solution, or if you need different editors to use wrapper for `<JsonEditor />`, for instance:
```
<div className="my-jsoneditor"><JsonEditor /></div>
```
so selector will be more specific.

**Comment by yinkh** [comment]
this work for me
```
            <Editor
              statusBar={true}
              search={true}
              mode={'code'}
              value={{'1': '1'}}
              htmlElementProps={{style: {height: 600}}}
            />
```
